name: engine-ex

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install Flask

    - name: Run tests
      run: |
        cd engine-ex
        python test_app.py
